[[source]]
url = "https://pypi.python.org/simple"
verify_ssl = true
name = "pypi"

[packages]
django = "<4.2,>=4.1.1"
asyncpg = ">=0.26,<0.27"
"psycopg2" = "<3.0,>=2.9.3"
pyyaml = "<7.0,>=6.0"
validators = ">=0.20,<0.21"
aiohttp = ">=3.7.3,<3.8"
"discord.py" = ">=1.3.4,<2.0"
python-dotenv = "<0.22,>=0.21"
python-dateutil = ">=2.8.1,<3.0"

[dev-packages]
black = "==22.8.0"
"flake8" = "*"
pylint = "<2.15" # pinned to 2.15 because of a pylint-django related bug https://github.com/PyCQA/pylint-django/issues/370pi
pylint-django = "*"
mypy = "*"
django-stubs = "==1.12.0"
types-pyyaml = "*"
types-chardet = "*"
types-python-dateutil = "*"

[requires]
python_version = "3.10"
